services:
    _defaults:
        autowire: true
        autoconfigure: true
    

Arminfrey\GeburtstagsmailBundle:
    resource: ../../src
    exclude: ../../src/{Model,Resources,Tests,Widget}
    arguments:
            - '@doctrine.dbal.account68_int_connection'
