services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Arminfrey\GeburtstagsmailBundle\:
        resource: ../src
        exclude: ../src/{Resources,Tests,Widget,contao/config}

    Arminfrey\GeburtstagsmailBundle\Service\SendMailService:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
