services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Arminfrey\ArminfreyGeburtstagsmailBundle:
        resource: ../../src
        exclude: ../../src/{Model,Resources,Tests,Widget}
        
       Arminfrey\GeburtstagsmailBundle\Service\SendMailService:
            arguments:
                $connection: '@doctrine.dbal.default_connection'
      
