services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

        
Arminfrey\ArminfreyGeburtstagsmailBundle:
    resource: ../../src
    exclude: ../../src/{Model,Resources,Tests,Widget}
    arguments:
           $connection: '@doctrine.dbal.account68_int_connection'
      
