services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Arminfrey\GeburtstagsmailBundle\Service\SendMailService:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
